/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zouheir
 */
import Connexion.Connexion;
import application.Consultation;
import application.Medical_record;
import application.Patient;
import application.Scanners;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Label;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
public class PanleInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanleInfo
     */
    public PanleInfo(){}
    CardLayout cardLayout;
    public PanleInfo(int codePatient,int idMedecin,JPanel panle){
        this.idMedecin=idMedecin;
        this.codePatient=codePatient;
        this.panel=panle;
        initComponents();
        affichage();
        cardLayout = (CardLayout)(this.getLayout());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextAreaDiscption1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jDate1 = new javax.swing.JTextField();
        jnom1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel_image2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxType1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jPanel_champ1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_champ1 = new javax.swing.JLabel();
        jTextADDRESS = new javax.swing.JTextField();
        jTextAGE = new javax.swing.JTextField();
        jLabel_champ2 = new javax.swing.JLabel();
        jText_TEL = new javax.swing.JTextField();
        jLabel_champ3 = new javax.swing.JLabel();
        jLabel_champ4 = new javax.swing.JLabel();
        jText_GENDER = new javax.swing.JTextField();
        jTextCIN = new javax.swing.JTextField();
        jLabel_champ6 = new javax.swing.JLabel();
        jLabel_EMAIL = new javax.swing.JLabel();
        jTextEMAIL = new javax.swing.JTextField();
        jTexG_Sang = new javax.swing.JTextField();
        jLabel_champ8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jText_nom_preom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultion = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableScanbers = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jnom = new javax.swing.JTextField();
        jDate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel_imgScanner = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextAreaDiscption = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextMOTIF = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextEXAM_RESULTS = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextDIA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        JtextORDONNANCE = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextdc = new javax.swing.JTextField();
        jTextDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jPanel14.setBackground(new java.awt.Color(41, 45, 62));

        jButton15.setText("Save");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Cancel");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jTextAreaDiscption1.setBackground(new java.awt.Color(250, 250, 250));
        jTextAreaDiscption1.setColumns(20);
        jTextAreaDiscption1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextAreaDiscption1.setForeground(new java.awt.Color(41, 45, 62));
        jTextAreaDiscption1.setRows(5);
        jTextAreaDiscption1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane21.setViewportView(jTextAreaDiscption1);

        jLabel26.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(250, 250, 250));
        jLabel26.setText("SCANNER");

        jDate1.setBackground(new java.awt.Color(153, 153, 153));
        jDate1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jDate1.setForeground(new java.awt.Color(250, 250, 250));
        jDate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDate1.setText("6/2/2021");
        jDate1.setBorder(null);
        jDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDate1jTextField10ActionPerformed(evt);
            }
        });

        jnom1.setBackground(new java.awt.Color(153, 153, 153));
        jnom1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jnom1.setForeground(new java.awt.Color(250, 250, 250));
        jnom1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnom1.setText("Zouheir");
        jnom1.setToolTipText("");
        jnom1.setBorder(null);
        jnom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnom1jTextField9ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(250, 250, 250));
        jLabel22.setText("DESCRIPTION");

        jLabel_image2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(250, 250, 250));
        jLabel23.setText("TYPE");

        jComboBoxType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LES MODALITÉS", "LA RADIOGRAPHIE PLANE", "LA RADIOGRAPHIE BASSE DOSE", "LA FLUOROSCOPIE", "LA MAMMOGRAPHIE", "LA TOMOGRAPHIE AXIALE", "L ÉCHOGRAPHIE" }));
        jComboBoxType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxType1ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(746, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addContainerGap(697, Short.MAX_VALUE)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(174, 174, 174))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)))
                    .addGap(22, 22, 22)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(98, 98, 98))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGap(0, 243, Short.MAX_VALUE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        setBackground(new java.awt.Color(41, 45, 62));
        setLayout(new java.awt.CardLayout());

        jPanelMain.setBackground(new java.awt.Color(41, 45, 62));
        jPanelMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMainMouseEntered(evt);
            }
        });

        jPanel_champ1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Details");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel_champ1.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ1.setText("ADDRESS");

        jTextADDRESS.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTextADDRESS.setForeground(new java.awt.Color(41, 45, 62));
        jTextADDRESS.setText("champ1");
        jTextADDRESS.setBorder(null);
        jTextADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextADDRESSActionPerformed(evt);
            }
        });

        jTextAGE.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTextAGE.setForeground(new java.awt.Color(41, 45, 62));
        jTextAGE.setText("champ1");
        jTextAGE.setBorder(null);
        jTextAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAGEActionPerformed(evt);
            }
        });

        jLabel_champ2.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ2.setText("AGE");

        jText_TEL.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jText_TEL.setForeground(new java.awt.Color(41, 45, 62));
        jText_TEL.setText("champ1");
        jText_TEL.setBorder(null);
        jText_TEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TELActionPerformed(evt);
            }
        });

        jLabel_champ3.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ3.setText("TEL/MOBIL");

        jLabel_champ4.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ4.setText("GENDER");

        jText_GENDER.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jText_GENDER.setForeground(new java.awt.Color(41, 45, 62));
        jText_GENDER.setText("champ1");
        jText_GENDER.setBorder(null);
        jText_GENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_GENDERActionPerformed(evt);
            }
        });

        jTextCIN.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTextCIN.setForeground(new java.awt.Color(41, 45, 62));
        jTextCIN.setText("champ1");
        jTextCIN.setBorder(null);
        jTextCIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCINActionPerformed(evt);
            }
        });

        jLabel_champ6.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ6.setText("CIN");

        jLabel_EMAIL.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_EMAIL.setText("EMAIL");

        jTextEMAIL.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTextEMAIL.setForeground(new java.awt.Color(41, 45, 62));
        jTextEMAIL.setText("champ1");
        jTextEMAIL.setBorder(null);
        jTextEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEMAILActionPerformed(evt);
            }
        });

        jTexG_Sang.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTexG_Sang.setForeground(new java.awt.Color(41, 45, 62));
        jTexG_Sang.setText("champ1");
        jTexG_Sang.setBorder(null);
        jTexG_Sang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexG_SangActionPerformed(evt);
            }
        });

        jLabel_champ8.setForeground(new java.awt.Color(27, 27, 20));
        jLabel_champ8.setText("GROUPE DE SANG");

        javax.swing.GroupLayout jPanel_champ1Layout = new javax.swing.GroupLayout(jPanel_champ1);
        jPanel_champ1.setLayout(jPanel_champ1Layout);
        jPanel_champ1Layout.setHorizontalGroup(
            jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_champ1Layout.createSequentialGroup()
                .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_champ3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_champ8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_champ1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jText_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_champ1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_champ1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jTextAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel_champ2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_champ1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel_champ6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_EMAIL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel_champ1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jText_TEL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextCIN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel_champ4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel_champ1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTexG_Sang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel_champ1Layout.setVerticalGroup(
            jPanel_champ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_champ1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_champ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_champ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_champ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_TEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_champ4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_champ6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_EMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_champ8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTexG_Sang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PHOTO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOM & Prenom");

        jText_nom_preom.setBackground(new java.awt.Color(153, 153, 153));
        jText_nom_preom.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jText_nom_preom.setForeground(new java.awt.Color(250, 250, 250));
        jText_nom_preom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_nom_preom.setText("Patint");
        jText_nom_preom.setBorder(null);
        jText_nom_preom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nom_preomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        jLabel3.setToolTipText("");

        jTextID.setBackground(new java.awt.Color(153, 153, 153));
        jTextID.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jTextID.setForeground(new java.awt.Color(250, 250, 250));
        jTextID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextID.setText("14");
        jTextID.setToolTipText("");
        jTextID.setBorder(null);
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_nom_preom, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(jTextID))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jText_nom_preom, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.setBackground(new java.awt.Color(41, 45, 62));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTableConsultion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Diagnostic", "Date  Consulte"
            }
        ));
        jTableConsultion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultion);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("History Consultations");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jScrollPane2.setViewportView(jPanel5);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTableScanbers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Date Scanner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableScanbers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScanbersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableScanbers);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("History Scanners");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_champ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addGap(327, 327, 327)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_champ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        add(jPanelMain, "card2");

        jPanel7.setBackground(new java.awt.Color(41, 45, 62));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jnom.setBackground(new java.awt.Color(153, 153, 153));
        jnom.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jnom.setForeground(new java.awt.Color(250, 250, 250));
        jnom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnom.setText("Zouheir");
        jnom.setToolTipText("");
        jnom.setBorder(null);
        jnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomjTextField9ActionPerformed(evt);
            }
        });

        jDate.setBackground(new java.awt.Color(153, 153, 153));
        jDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jDate.setForeground(new java.awt.Color(250, 250, 250));
        jDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDate.setText("6/2/2021");
        jDate.setBorder(null);
        jDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatejTextField10ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(250, 250, 250));
        jLabel21.setText("TYPE");

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LES MODALITÉS", "LA RADIOGRAPHIE PLANE", "LA RADIOGRAPHIE BASSE DOSE", "LA FLUOROSCOPIE", "LA MAMMOGRAPHIE", "LA TOMOGRAPHIE AXIALE", "L ÉCHOGRAPHIE" }));
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabel_imgScanner.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel25.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(250, 250, 250));
        jLabel25.setText("SCANNER");

        jTextAreaDiscption.setBackground(new java.awt.Color(250, 250, 250));
        jTextAreaDiscption.setColumns(20);
        jTextAreaDiscption.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextAreaDiscption.setForeground(new java.awt.Color(41, 45, 62));
        jTextAreaDiscption.setRows(5);
        jTextAreaDiscption.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane20.setViewportView(jTextAreaDiscption);

        jLabel20.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(250, 250, 250));
        jLabel20.setText("DESCRIPTION");

        jButton7.setBackground(new java.awt.Color(250, 250, 250));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(41, 45, 62));
        jButton7.setText("Save");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jnom, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane20)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_imgScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jnom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_imgScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        add(jPanel7, "card3");

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel12.setBackground(new java.awt.Color(41, 45, 62));
        jPanel12.setPreferredSize(new java.awt.Dimension(1147, 1000));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(41, 45, 62));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(41, 45, 62));
        jPanel13.setPreferredSize(new java.awt.Dimension(1147, 1000));

        jTextMOTIF.setBackground(new java.awt.Color(250, 250, 250));
        jTextMOTIF.setColumns(20);
        jTextMOTIF.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextMOTIF.setForeground(new java.awt.Color(41, 45, 62));
        jTextMOTIF.setRows(5);
        jTextMOTIF.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane6.setViewportView(jTextMOTIF);

        jLabel8.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 250, 250));
        jLabel8.setText("MOTIF");

        jLabel9.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 250, 250));
        jLabel9.setText("EXAM RESULTS");

        jTextEXAM_RESULTS.setBackground(new java.awt.Color(250, 250, 250));
        jTextEXAM_RESULTS.setColumns(20);
        jTextEXAM_RESULTS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextEXAM_RESULTS.setForeground(new java.awt.Color(41, 45, 62));
        jTextEXAM_RESULTS.setRows(5);
        jTextEXAM_RESULTS.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane7.setViewportView(jTextEXAM_RESULTS);

        jTextDIA.setBackground(new java.awt.Color(250, 250, 250));
        jTextDIA.setColumns(20);
        jTextDIA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextDIA.setForeground(new java.awt.Color(41, 45, 62));
        jTextDIA.setRows(5);
        jTextDIA.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane8.setViewportView(jTextDIA);

        jLabel11.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(250, 250, 250));
        jLabel11.setText("DIAGNOSTIC");

        JtextORDONNANCE.setBackground(new java.awt.Color(250, 250, 250));
        JtextORDONNANCE.setColumns(20);
        JtextORDONNANCE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JtextORDONNANCE.setForeground(new java.awt.Color(41, 45, 62));
        JtextORDONNANCE.setRows(5);
        JtextORDONNANCE.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jScrollPane9.setViewportView(JtextORDONNANCE);

        jLabel12.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 250, 250));
        jLabel12.setText("ORDONNANCE");

        jTextdc.setBackground(new java.awt.Color(153, 153, 153));
        jTextdc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextdc.setForeground(new java.awt.Color(250, 250, 250));
        jTextdc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextdc.setText("D.Zouheir");
        jTextdc.setToolTipText("");
        jTextdc.setBorder(null);
        jTextdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdcActionPerformed(evt);
            }
        });

        jTextDate.setBackground(new java.awt.Color(153, 153, 153));
        jTextDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextDate.setForeground(new java.awt.Color(250, 250, 250));
        jTextDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextDate.setText("6/2/2021");
        jTextDate.setBorder(null);
        jTextDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDateActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jTextdc, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextdc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(465, 465, 465))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(865, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane5.setViewportView(jPanel12);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        add(jPanel8, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jText_nom_preomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nom_preomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nom_preomActionPerformed

    private void jTexG_SangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexG_SangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexG_SangActionPerformed

    private void jTextEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEMAILActionPerformed

    private void jTextCINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCINActionPerformed

    private void jText_GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_GENDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_GENDERActionPerformed

    private void jText_TELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TELActionPerformed

    private void jTextAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAGEActionPerformed

    private void jTextADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextADDRESSActionPerformed

    private void jTableConsultionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultionMouseClicked
            if(evt.getClickCount()==1 && !evt.isConsumed()){
           evt.consume();
        int i=jTableConsultion.getSelectedRow();
              
     
        int j= (int) jTableConsultion.getModel().getValueAt(i, 0);
                this.codeConsultation=j;
               afficher(codeConsultation);
               cardLayout.show(this, "card4");

            }
    }//GEN-LAST:event_jTableConsultionMouseClicked
FScanners panle ;
    private void jTableScanbersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScanbersMouseClicked
          if(evt.getClickCount()==1 && !evt.isConsumed()){
           evt.consume();
        int i=jTableScanbers.getSelectedRow();
        int j= (int) jTableScanbers.getModel().getValueAt(i, 0);
             
              this.idSC=j;
               affichageScanner(idSC);
               cardLayout.show(this, "card3");
            }
    }//GEN-LAST:event_jTableScanbersMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        this.setVisible(false);
        this.back=true;
        panel.setVisible(back);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanelMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelMainMouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
affichage();
cardLayout.show(this, "card2");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDateActionPerformed

    private void jTextdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdcActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
affichage();
cardLayout.show(this, "card2");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jnomjTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomjTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomjTextField9ActionPerformed

    private void jDatejTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatejTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatejTextField10ActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Connexion connexion = new Connexion();
        String req="";
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        panel.isDisplayable();
        this.back=true;
        panel.setVisible(back);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jDate1jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDate1jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDate1jTextField10ActionPerformed

    private void jnom1jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnom1jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnom1jTextField9ActionPerformed

    private void jComboBoxType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxType1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);

        this.back=true;
        panel.setVisible(back);

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        boolean ischange=false;
        Scanners sc = new Scanners();
        sc.getScanners(idSC);
        
        ischange=(!jTextAreaDiscption.getText().trim().equals(sc.getDescription().trim()) || !jComboBoxType.getSelectedItem().toString().trim().equals(sc.getType_Scanners().trim())); 
        
        if(ischange){ 
           sc.setDescription(jTextAreaDiscption.getText());
           sc.setType_Scanners(jComboBoxType.getSelectedItem().toString());
            sc.UPdateScanners(idSC,"");
        }
        affichage();
         cardLayout.show(this, "card2");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Consultation cslt = new Consultation();
     
      cslt.setMotif(jTextMOTIF.getText());
      cslt.setDiagnostic(jTextDIA.getText());
      cslt.setResultExam(jTextEXAM_RESULTS.getText());
      cslt.UPdateCon(codeConsultation);
        Connexion cnx = new Connexion();
        String reqOrd="UPDATE `mydoctor`.`ordonnance` SET `dateOrdonnance`=now(), `contenuOrdonnance`="+JtextORDONNANCE.getText()+" WHERE  `codeOrdonnance`="+cslt.getCodeOrdonnance();
        cnx.reqUpdate(reqOrd);
         affichage();
         cardLayout.show(this, "card2");
    }//GEN-LAST:event_jButton1ActionPerformed
public  void afficher(int codeConsultation){
        try {
            
            
            String req="SELECT `nomMedecin` FROM `mydoctor`.`medecin` WHERE `idMedecin` = "+idMedecin;
            Connexion cnx =new Connexion();
            ResultSet rs=cnx.reqSelection(req);
            while(rs.next()){
               jTextdc.setText("D."+rs.getString(1)); ;
            }   } catch (SQLException ex) {
            Logger.getLogger(Fconsultation.class.getName()).log(Level.SEVERE, null, ex);
        }
     Consultation cnsl=new Consultation();
    cnsl.getCon(codeConsultation);
    jTextDate.setText(cnsl.getDateConsultation().toString());
String req="SELECT `contenuOrdonnance` FROM `mydoctor`.`ordonnance` WHERE `codeOrdonnance` = "+cnsl.getCodeOrdonnance();
 Connexion cnx =new Connexion();
            ResultSet rs=cnx.reqSelection(req);
        try {
            while(rs.next()){
                JtextORDONNANCE.setText(rs.getString(1)); ;
            }    
        } catch (SQLException ex) {
            Logger.getLogger(Fconsultation.class.getName()).log(Level.SEVERE, null, ex);
        }


    jTextMOTIF.setText(cnsl.getMotif());
    jTextEXAM_RESULTS.setText(cnsl.getResultExam());
    jTextDIA.setText(cnsl.getDiagnostic());
    
}
    public void affichage(){
        this.RM= new Medical_record(this.idMedecin,this.codePatient);
        Patient Pt=new Patient();
        Pt.getPatientbyid(this.codePatient);
        jText_nom_preom.setText(Pt.getNomPatient()+" "+Pt.getPrenomPatient());
        jTextID.setText(Pt.getCodePatient().toString());
        jText_TEL.setText(Pt.getTelPatient().toString());
        jTextADDRESS.setText(Pt.getAdressePatient());
        jTextAGE.setText(Pt.getAge().toString());
     
      
        jTextCIN.setText(Pt.getCIN());
        jText_GENDER.setText(Pt.getSexe());
        jTextEMAIL.setText(Pt.getAdressePatient());
        jTexG_Sang.setText(Pt.getGsang());
       ImageIcon Img =new ImageIcon(Pt.getImage());
       Image  im = Img.getImage();
       jLabel_image.setSize( 215,166);
        System.out.println(jLabel_image.getWidth());
        System.out.println(jLabel_image.getHeight());
       Image  myimage = im.getScaledInstance(jLabel_image.getWidth(),jLabel_image.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(myimage);
       jLabel_image.setIcon(image);
       
       //
       DefaultTableModel model1 = (DefaultTableModel) jTableConsultion.getModel();
       model1.setRowCount(0);
        for (Consultation consultation : RM.getList_Consultations()) {
         

    

    Vector row = new Vector();
    row.add(consultation.getCodeConsultation());
            
    row.add(consultation.getDiagnostic());
    row.add(consultation.getDateConsultation());
    System.out.println(row);
    model1.addRow(row);
        }
         DefaultTableModel model2 = (DefaultTableModel) jTableScanbers.getModel();
  model2.setRowCount(0);
        for (Scanners scanner : RM.getList_Scanners()) {
            Vector row = new Vector();
            row.add(scanner.getIdSC());
            row.add(scanner.getType_Scanners());
            row.add(scanner.getDate_Scanners());
            System.out.println(row.isEmpty());
            model2.addRow(row);
        }
      
       //
    }
    
    public void affichageScanner(int idSC)
   {
   Scanners sc= new Scanners();
   sc.getScanners(idSC);
   jComboBoxType.setSelectedItem(sc.getType_Scanners());
   jTextAreaDiscption.setText(sc.getDescription());
   jnom.setText("ID : "+sc.getCodePatient());
   jDate.setText(sc.getDate_Scanners().toString());
   ImageIcon Img =new ImageIcon(sc.getImage_Scanners());
       Image  im = Img.getImage();
      // jLabel_imgScanner.setSize(476,330);
        
       Image  myimage = im.getScaledInstance(jLabel_imgScanner.getWidth(),jLabel_imgScanner.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(myimage);
       jLabel_imgScanner.setIcon(image);
   
   }
    

 private Medical_record RM;

    public int getCodePatient() {
        return codePatient;
    }

    public void setCodePatient(int codePatient) {
        this.codePatient = codePatient;
    }

    public int getIdMedecin() {
        return idMedecin;
    }

    public void setIdMedecin(int idMedecin) {
        this.idMedecin = idMedecin;
    }
 private int codePatient ;
 private int idMedecin;

    public boolean isBack() {
        return back;
    }

    public void setBack(boolean back) {
        this.back = back;
    }
    private int idSC;
    private int codeConsultation;
 private boolean back=false;
 private JPanel panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtextORDONNANCE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxType1;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_EMAIL;
    private javax.swing.JLabel jLabel_champ1;
    private javax.swing.JLabel jLabel_champ2;
    private javax.swing.JLabel jLabel_champ3;
    private javax.swing.JLabel jLabel_champ4;
    private javax.swing.JLabel jLabel_champ6;
    private javax.swing.JLabel jLabel_champ8;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_image2;
    private javax.swing.JLabel jLabel_imgScanner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanel_champ1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableConsultion;
    private javax.swing.JTable jTableScanbers;
    private javax.swing.JTextField jTexG_Sang;
    private javax.swing.JTextField jTextADDRESS;
    private javax.swing.JTextField jTextAGE;
    private javax.swing.JTextArea jTextAreaDiscption;
    private javax.swing.JTextArea jTextAreaDiscption1;
    private javax.swing.JTextField jTextCIN;
    private javax.swing.JTextArea jTextDIA;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextEMAIL;
    private javax.swing.JTextArea jTextEXAM_RESULTS;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextArea jTextMOTIF;
    private javax.swing.JTextField jText_GENDER;
    private javax.swing.JTextField jText_TEL;
    private javax.swing.JTextField jText_nom_preom;
    private javax.swing.JTextField jTextdc;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jnom1;
    // End of variables declaration//GEN-END:variables
}
