
import Connexion.Connexion;
import application.Consultation;
import application.Medical_record;
import application.Patient;
import application.Scanners;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zouheir
 */

public class Window_Patient extends javax.swing.JFrame {
    
    private String login;
    private String password;
    private int ID_patient;
    private DefaultTableModel modelConsultion ;
    private DefaultTableModel modelScanner;
    private HashMap<Integer,Integer> HashMapConsultion = new HashMap();
    private HashMap<Integer,Integer> HashMapScanner = new HashMap();
    private ResultSet rs;
    private ResultSet rs1;
    CardLayout cardLayoutpatient;
    /*String diagnostic;
    String dat;
    String motif;
    String Doctor;
    String ordonnance;
    String resultExam;*/
    /*private ArrayList<String> Diagnostic;
    private ArrayList<Integer> ID_pat;
    private ArrayList<String> dat;
    private ArrayList<String> motif;
    private ArrayList<String> Doctor;
    private ArrayList<String> ordonnance;
    private ArrayList<String> resultExam;*/
  
    /**
     * Creates new form Main_APS
     */
    
 // white border for the menu    
 Border B_White = BorderFactory.createMatteBorder(1,0,1,0,new Color(250,250,250));
 // default border for the menu   
 Border dfault_border = BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(15,17,26));
 // create array of menulablesF
    JLabel[] menuLabels = new JLabel[3]; // 4 nb of the label the menu     
 
 // create array of jpanles
    JPanel[] Panels = new JPanel[3]; // 4 nb of the Panel aso a the menu   

    
    public Window_Patient(int codePatient) {
 this.ID_patient=codePatient;
        
        initComponents();
        
        cardLayoutpatient = (CardLayout)(Container.getLayout());
        // popilate the menulabls array
        menuLabels[0]=jLabel_menuIem1;
        menuLabels[1]=jLabel_menuIem2;
        
        menuLabels[2]=jLabel_menuIem4;
        // popilate the menulabls array\
        //
        Panels[0]=jPanel_Iem1;
        Panels[1]=jPanel_Iem2;
        
        Panels[2]=jPanel_Iem4;
      
       // jPanel2.setVisible(false);
        

        addActionToMenuLabels();
        
        jScrollPane2.setViewportView(jTable1);
//        d=(DefaultTableModel)jTable1.getModel();
//        cons=(DefaultTableModel)jTableconsultation.getModel();
//        scanner=(DefaultTableModel)jTableScanner.getModel();
        affichage();

    }
    public void setLogin(String login){
        this.login=login;
    }
    public void setpassword(String password){
        this.password=password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_menuIem1 = new javax.swing.JLabel();
        jLabel_menuIem2 = new javax.swing.JLabel();
        jLabel_menuIem4 = new javax.swing.JLabel();
        jlabel_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_close1 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        jPanel_Iem1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        images = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableconsultation = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableScanner = new javax.swing.JTable();
        jTexfirstName = new javax.swing.JTextField();
        jTextlastName = new javax.swing.JTextField();
        jTextage = new javax.swing.JTextField();
        jTextsexe = new javax.swing.JTextField();
        jTextbloodGroup = new javax.swing.JTextField();
        jTexAdresse = new javax.swing.JTextField();
        jTextphoneNumber = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel_Iem2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel_Iem4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextMOTIF = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextEXAM_RESULTS = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextDIAGNOSTIC = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextORDONNANCE = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextDESCRIPTION = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(41, 45, 62));

        jPanel4.setBackground(new java.awt.Color(15, 17, 26));
        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentHidden(evt);
            }
        });

        jLabel_menuIem1.setBackground(new java.awt.Color(15, 17, 26));
        jLabel_menuIem1.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel_menuIem1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel_menuIem1.setText("Status");
        jLabel_menuIem1.setToolTipText("");
        jLabel_menuIem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_menuIem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_menuIem1.setOpaque(true);

        jLabel_menuIem2.setBackground(new java.awt.Color(15, 17, 26));
        jLabel_menuIem2.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel_menuIem2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel_menuIem2.setText("Schedul");
        jLabel_menuIem2.setOpaque(true);

        jLabel_menuIem4.setBackground(new java.awt.Color(15, 17, 26));
        jLabel_menuIem4.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel_menuIem4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel_menuIem4.setText("Logout");
        jLabel_menuIem4.setOpaque(true);
        jLabel_menuIem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menuIem4MouseClicked(evt);
            }
        });

        jlabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/doctor.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("MyDoctor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlabel_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_menuIem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_menuIem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_menuIem4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlabel_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(jLabel_menuIem1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_menuIem2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_menuIem4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel_menuIem1, jLabel_menuIem2, jLabel_menuIem4});

        jPanel6.setBackground(new java.awt.Color(41, 45, 62));

        jLabel_close1.setBackground(new java.awt.Color(41, 45, 62));
        jLabel_close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/x.png"))); // NOI18N
        jLabel_close1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_close1.setOpaque(true);
        jLabel_close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel_close1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Container.setLayout(new java.awt.CardLayout());

        jPanel_Iem1.setBackground(new java.awt.Color(41, 45, 62));

        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableconsultation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "diagnostic", "date consultation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableconsultation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableconsultationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableconsultation);
        if (jTableconsultation.getColumnModel().getColumnCount() > 0) {
            jTableconsultation.getColumnModel().getColumn(0).setResizable(false);
            jTableconsultation.getColumnModel().getColumn(1).setResizable(false);
        }

        jTableScanner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Date Scanner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableScanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScannerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableScanner);
        if (jTableScanner.getColumnModel().getColumnCount() > 0) {
            jTableScanner.getColumnModel().getColumn(0).setResizable(false);
            jTableScanner.getColumnModel().getColumn(1).setResizable(false);
        }

        jTexfirstName.setEditable(false);
        jTexfirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextlastName.setEditable(false);
        jTextlastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextage.setEditable(false);
        jTextage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextsexe.setEditable(false);
        jTextsexe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextbloodGroup.setEditable(false);
        jTextbloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTexAdresse.setEditable(false);
        jTexAdresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextphoneNumber.setEditable(false);
        jTextphoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextID.setEditable(false);
        jTextID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextEmail.setEditable(false);
        jTextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("patientID");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("firstName");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("lastName");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("age");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("sexe");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bloodGroup");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Adresse");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("phoneNumber");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email");

        javax.swing.GroupLayout jPanel_Iem1Layout = new javax.swing.GroupLayout(jPanel_Iem1);
        jPanel_Iem1.setLayout(jPanel_Iem1Layout);
        jPanel_Iem1Layout.setHorizontalGroup(
            jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTexfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextlastName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextage, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextsexe, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextbloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextphoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTexAdresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(images, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
        );

        jPanel_Iem1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTexAdresse, jTexfirstName, jTextEmail, jTextID, jTextage, jTextbloodGroup, jTextlastName, jTextphoneNumber, jTextsexe});

        jPanel_Iem1Layout.setVerticalGroup(
            jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(images, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextlastName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextage, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextsexe, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextbloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_Iem1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTexAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextphoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Iem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanel_Iem1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTexAdresse, jTexfirstName, jTextEmail, jTextID, jTextage, jTextbloodGroup, jTextlastName, jTextphoneNumber, jTextsexe});

        Container.add(jPanel_Iem1, "cardmain");

        jPanel_Iem2.setBackground(new java.awt.Color(250, 250, 250));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor", "Date", "Hours", "specialité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Iem2Layout = new javax.swing.GroupLayout(jPanel_Iem2);
        jPanel_Iem2.setLayout(jPanel_Iem2Layout);
        jPanel_Iem2Layout.setHorizontalGroup(
            jPanel_Iem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Iem2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Iem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Iem2Layout.createSequentialGroup()
                        .addGap(1042, 1042, 1042)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel_Iem2Layout.setVerticalGroup(
            jPanel_Iem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Iem2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        Container.add(jPanel_Iem2, "card4");

        jPanel_Iem4.setBackground(new java.awt.Color(20, 240, 240));

        javax.swing.GroupLayout jPanel_Iem4Layout = new javax.swing.GroupLayout(jPanel_Iem4);
        jPanel_Iem4.setLayout(jPanel_Iem4Layout);
        jPanel_Iem4Layout.setHorizontalGroup(
            jPanel_Iem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
        );
        jPanel_Iem4Layout.setVerticalGroup(
            jPanel_Iem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        Container.add(jPanel_Iem4, "card5");

        jPanel1.setBackground(new java.awt.Color(41, 45, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1257, 747));

        jLabel2.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MOTIF");

        jTextMOTIF.setEditable(false);
        jTextMOTIF.setColumns(20);
        jTextMOTIF.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jTextMOTIF.setRows(5);
        jScrollPane5.setViewportView(jTextMOTIF);

        jLabel4.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("EXAM RESULTS");

        jTextEXAM_RESULTS.setEditable(false);
        jTextEXAM_RESULTS.setColumns(20);
        jTextEXAM_RESULTS.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jTextEXAM_RESULTS.setRows(5);
        jScrollPane6.setViewportView(jTextEXAM_RESULTS);

        jLabel5.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIAGNOSTIC");

        jLabel6.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ORDONNANCE");

        jTextDIAGNOSTIC.setEditable(false);
        jTextDIAGNOSTIC.setColumns(20);
        jTextDIAGNOSTIC.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jTextDIAGNOSTIC.setRows(5);
        jScrollPane7.setViewportView(jTextDIAGNOSTIC);

        jTextORDONNANCE.setEditable(false);
        jTextORDONNANCE.setColumns(20);
        jTextORDONNANCE.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 14)); // NOI18N
        jTextORDONNANCE.setRows(5);
        jScrollPane8.setViewportView(jTextORDONNANCE);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setBorder(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField2, jTextField3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField2, jTextField3});

        Container.add(jPanel1, "card5");

        jPanel3.setBackground(new java.awt.Color(41, 45, 62));

        jLabel3.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Scanner");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCRIPTION");

        jTextDate.setBackground(new java.awt.Color(41, 45, 62));
        jTextDate.setFont(new java.awt.Font("VictorMono Nerd Font Mono", 1, 24)); // NOI18N
        jTextDate.setForeground(new java.awt.Color(240, 240, 240));
        jTextDate.setBorder(null);

        jTextDESCRIPTION.setEditable(false);
        jTextDESCRIPTION.setColumns(20);
        jTextDESCRIPTION.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextDESCRIPTION.setForeground(new java.awt.Color(41, 45, 62));
        jTextDESCRIPTION.setRows(5);
        jTextDESCRIPTION.setBorder(null);
        jScrollPane9.setViewportView(jTextDESCRIPTION);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ back_arrow.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(400, 400, 400)
                        .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        Container.add(jPanel3, "card6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close1MouseClicked
        // close this from
        this.dispose();
    }//GEN-LAST:event_jLabel_close1MouseClicked

    private void jPanel4ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4ComponentHidden

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{

//            d.setNumRows(0);
            
            Connexion con=new Connexion();
            Connection con1=con.Cnx;
            Statement st=con.St;
//          
//                System.out.println("codePat="+res.getInt(1));
                
            PreparedStatement ps=con.Cnx.prepareStatement("SELECT R.* ,M.specialite ,Concat('Dr. ',M.nomMedecin,' ',M.prenomMedecin) AS FullName From rdv R,medecin M WHERE R.idMedecin=M.idMedecin and `codePatient`=? and R.dateRDV >= now();");
               ps.setInt(1,ID_patient);
               ResultSet rs=ps.executeQuery();
                DefaultTableModel modelConsultion = (DefaultTableModel) jTable1.getModel();
                 modelConsultion.setRowCount(0);
                    while(rs.next()) {
                    Vector row = new Vector();
                    Timestamp date=rs.getTimestamp("dateRDV");
                    SimpleDateFormat    sdf= new SimpleDateFormat("dd/MM/yyyy");
                    SimpleDateFormat    sdf2= new SimpleDateFormat("hh:mm");           
                    String Doctor=rs.getString("FullName");
                   
                    String specialite=rs.getString("specialite");
                    row.add(Doctor);
                    row.add(sdf.format(date));
                    row.add(sdf2.format(date));
                    
                    row.add(specialite);
                    modelConsultion.addRow(row);
                    }
                     
                     
//                while(rs.next()){
////                    System.out.println("true");
//                    String ID_patient=rs.getString(2);
////                    System.out.println("id="+ID_patient);
//                    Date date=rs.getDate(1);
//                    
//                    
//                    String Doctor=rs.getString(5);
//                    String Hours=date.getHours()+":"+date.getMinutes();
//                    String dat=date.getDay()+"/"+date.getMonth()+"/"+date.getYear();
//                    String specialite=rs.getString("specialite");
//                    String inf[]={Doctor,dat,Hours,ID_patient,specialite};
//                    d.addRow(inf);
//
//                    System.out.println("id="+ID_patient);
//
//                }
            
        }catch(Exception e){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
          
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addRdv AddRdv=new addRdv(ID_patient);
        AddRdv.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void affichage(){
      
        try {
            // this.RM= new Medical_record(this.idMedecin,this.codePatient);
            Patient Pt=new Patient();
            Pt.getPatientbyid(this.ID_patient);
            jTexfirstName.setText(Pt.getNomPatient());
            jTextlastName.setText(Pt.getPrenomPatient());
            jTextID.setText(Pt.getCodePatient().toString());
            jTextphoneNumber.setText(Pt.getTelPatient().toString());
            jTexAdresse.setText(Pt.getAdressePatient());
            jTextage.setText(Pt.getAge().toString());
            
            
            jTextID.setText(Pt.getCodePatient().toString());
            jTextsexe.setText(Pt.getSexe());
            jTextEmail.setText(Pt.getAdressePatient());
            jTextbloodGroup.setText(Pt.getGsang());
            ImageIcon Img =new ImageIcon(Pt.getImage());
            Image  im = Img.getImage();
            Image  myimage = im.getScaledInstance(images.getWidth(),images.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(myimage);
            images.setIcon(image);
            
            Connexion cnx = new Connexion();
            PreparedStatement ps =cnx.Cnx.prepareStatement("SELECT * FROM `mydoctor`.`consultation` WHERE `codePatient` = ?");
            ps.setInt(1,ID_patient);
            rs=ps.executeQuery();
            modelConsultion = (DefaultTableModel) jTableconsultation.getModel();
            modelConsultion.setRowCount(0);
           int i=0;
            while(rs.next()){
                HashMapConsultion.put(i,rs.getInt("codeConsultation"));
                Vector row = new Vector();
                row.add(rs.getString("diagnostic"));
                row.add(rs.getTimestamp("dateConsultation"));
                modelConsultion.addRow(row);
                i++;
            }
            modelScanner = (DefaultTableModel) jTableScanner.getModel();
            modelScanner.setRowCount(0);
            PreparedStatement ps1 =cnx.Cnx.prepareStatement("SELECT * FROM `mydoctor`.`scanners` WHERE `codePatient` = ?");
           
            ps1.setInt(1,ID_patient);
            System.out.println(ps1);
            rs1=ps1.executeQuery();
            int j=0;
            while(rs1.next()) {
                HashMapScanner.put(j,rs1.getInt("idSC"));
                Vector row = new Vector();
                row.add(rs1.getString("Type_Scanners"));
                row.add(rs1.getDate("date_Scanners"));
                modelScanner.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Window_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
 
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTableconsultationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableconsultationMouseClicked
        try {
            int diag =jTableconsultation.getSelectedRow();
            int id= HashMapConsultion.get(diag);
             rs.beforeFirst();
            while(rs.next()){
              
            if(rs.getInt("codeConsultation") == id){
            
            jTextMOTIF.setText(rs.getString("motif"));
            Connexion cnx = new Connexion(); 
            ResultSet res;
            PreparedStatement prs=cnx.Cnx.prepareStatement("SELECT Concat('Dr. ',M.nomMedecin,' ',M.prenomMedecin) AS FullName  from rdv R, medecin M WHERE R.idMedecin=M.idMedecin and R.codeRDV = ?;");
            prs.setInt(1, rs.getInt("codeRDV"));
            res=prs.executeQuery();
            if(res.next()){
             jTextField2.setText(res.getString("FullName"));
              
            }
            jTextField3.setText(rs.getTimestamp("dateConsultation").toString()); 
            jTextEXAM_RESULTS.setText(rs.getString("resultExam"));
            jTextDIAGNOSTIC.setText(rs.getString("diagnostic"));
            ResultSet res1;
            PreparedStatement prs1=cnx.Cnx.prepareStatement("SELECT contenuOrdonnance FROM ordonnance WHERE codeOrdonnance=?;");
            prs1.setInt(1, rs.getInt("codeOrdonnance"));
            res1=prs1.executeQuery();
            
            if(res1.next()){
                jTextORDONNANCE.setText(res1.getString("contenuOrdonnance"));
            }
             
            }
              
            }
             cardLayoutpatient.show(Container,"card5"); 
        } catch (SQLException ex) {
            Logger.getLogger(Window_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableconsultationMouseClicked

    private void jTableScannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScannerMouseClicked
 try {
            int diag =jTableScanner.getSelectedRow();
            int id= HashMapScanner.get(diag);
            System.out.println("aaa");
            rs1.beforeFirst();
            System.out.println("bbb");
            while(rs1.next()){  
            if(rs1.getInt("idSC") == id){
            this.jTextDate.setText(rs1.getDate("date_Scanners").toString());
            this.jTextDESCRIPTION.setText(rs1.getString("description"));
             ImageIcon Img =new ImageIcon(rs1.getBytes("Image_Scanners"));
            Image  im = Img.getImage();
            Image  myimage = im.getScaledInstance(jLabelImage.getWidth(),jLabelImage.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(myimage);
            jLabelImage.setIcon(image);
            }  
            }
             cardLayoutpatient.show(Container,"card6"); 
        } catch (SQLException ex) {
            Logger.getLogger(Window_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableScannerMouseClicked

    private void jLabel_menuIem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menuIem4MouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel_menuIem4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
 cardLayoutpatient.show(Container,"cardmain"); 
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
cardLayoutpatient.show(Container,"cardmain");         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    // creat function  to Show the selected  panel
public void showPanel(JPanel panel){
    
    for (JPanel pnl : Panels) {
        
        pnl.setVisible(false);
    }
    panel.setVisible(true);
} 
public void   setLabelBackround(JLabel label){
    // rest Label to theit default
    for (JLabel meunItem : menuLabels) {
        meunItem.setBackground(new Color(15,17,26));
    }
    
    
    // change the Jlabl Background color
        label.setBackground(new Color(41,45,62));
}
    
    
public void addActionToMenuLabels()
{
    //get labels in the jpanel menu
    Component[] components = jPanel4.getComponents();
    for (Component component : components) {
        
        if(component instanceof JLabel)
        {
                JLabel label = (JLabel) component;
                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent me) {
                        // change the Jlabl Background color
                        
                        setLabelBackround(label);
                        switch (label.getText().trim()){
                            case"Status": 
                                
                                    
                                    showPanel(Panels[0]);
                                    break;
                            case"Schedul": 
                                    showPanel(Panels[1]);
                                    break;
                            
                        }
                        
                    }

                    @Override
                    public void mousePressed(MouseEvent me) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent me) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent me) {
                        // set Borde 
                        label.setBorder(B_White);
                    }

                    @Override
                    public void mouseExited(MouseEvent me) {
                     // set Borde 
                        label.setBorder(dfault_border);

                    }
                });
        }
        
    }

}
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main_app().setVisible(true);
//            }
//        });   
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JLabel images;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabel_close1;
    private javax.swing.JLabel jLabel_menuIem1;
    private javax.swing.JLabel jLabel_menuIem2;
    private javax.swing.JLabel jLabel_menuIem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Iem1;
    private javax.swing.JPanel jPanel_Iem2;
    private javax.swing.JPanel jPanel_Iem4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableScanner;
    private javax.swing.JTable jTableconsultation;
    private javax.swing.JTextField jTexAdresse;
    private javax.swing.JTextField jTexfirstName;
    private javax.swing.JTextArea jTextDESCRIPTION;
    private javax.swing.JTextArea jTextDIAGNOSTIC;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextArea jTextEXAM_RESULTS;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextArea jTextMOTIF;
    private javax.swing.JTextArea jTextORDONNANCE;
    private javax.swing.JTextField jTextage;
    private javax.swing.JTextField jTextbloodGroup;
    private javax.swing.JTextField jTextlastName;
    private javax.swing.JTextField jTextphoneNumber;
    private javax.swing.JTextField jTextsexe;
    private javax.swing.JLabel jlabel_icon;
    // End of variables declaration//GEN-END:variables
}
